services:
  CheckInfo:
    image: showjimzc/checkinfotool:latest
    pull_policy: always
    container_name: checkInfoTool
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/jerry/workDir:/app/workDir
      - /home/jerry/Output:/app/Output
    restart: always
    ports:
      - 8502:8501
